services:
    # === Database ===
    db:
        restart: always
        build:
            context: ./datasources/bead_postgres
            dockerfile: Dockerfile
        environment:
            POSTGRES_DB: bead
            POSTGRES_USER: ${USER}
            POSTGRES_PASSWORD: ${PASSWORD}
        ports:
            - 5432:5432
        networks:
            - bead-network
        volumes:
            - bead_db:/var/lib/postgresql/data
    # === Web ===
    web:
        build:
            context: ./web
            dockerfile: Dockerfile

# === Volumes (DB) ===
volumes:
    bead_db:

# === Network ===
networks:
    bead-network:
        driver: bridge
        name: bead-network
