input:
  http_client:
    url: ${SCRIPT_URL}/taxi-availability
    verb: GET
    rate_limit: once_per_minute

pipeline:
  processors:
    - unarchive:
        format: json_array
output:
  label: ""
  broker:
    pattern: fan_out
    outputs:
      - resource: store_taxi_availability_location_in_csv
        processors:
          - resource: taxi_availability_to_csv

rate_limit_resources:
  - label: once_per_day
    local:
      count: 1
      interval: 86400s
  - label: once_per_minute
    local:
      count: 1
      interval: 1m

output_resources:
  - label: store_taxi_availability_location_in_csv
    file:
      path: /csv/taxi_availability_${! now().ts_strftime("%y-%m-%d", "Singapore") }.csv
      codec: lines

processor_resources:
  - label: taxi_availability_to_csv
    mapping: |
      root = "%s,%v,%v,%v".format(this.b_id, this.created_at, this.lon, this.lat)
