input:
  http_client:
    url: ${SCRIPT_URL}/taxi-availability
    verb: GET
    rate_limit: once_per_minute

pipeline:
  processors:
    - unarchive:
        format: json_array
output:
  label: ""
  broker:
    pattern: fan_out
    outputs:
      - resource: store_taxi_availability_location_in_database
      - resource: publish_taxi_availability_to_kafka
