input:
  http_client:
    url: "${SCRIPT_URL}/districts"
    verb: GET
    rate_limit: once_per_day

pipeline:
  processors:
    - unarchive:
        format: json_array

output:
  label: "onemap_to_postgres"
  sql_raw:
    driver: postgres
    dsn: postgres://${USER}:${PASSWORD}@${DATABASE_HOST}:5432/bead?sslmode=disable
    query: INSERT INTO districts (name, location) VALUES ($1, ST_GeomFromGeoJSON($2)) ON CONFLICT (name) DO UPDATE SET location = ST_GeomFromGeoJSON($2)
    args_mapping: |
      root = [ this.pln_area_n, this.geojson ]
